export const enum StackMenu {
  BottomTabNavigator = 'BottomTabNavigator',
  DatePick = 'DatePick',
  OpenEvent = 'OpenEvent',
  CategoryEvent = 'CategoryEvent',
  BookmarkEvent = 'BookmarkEvent',
  PopularEvent = 'PopularEvent',
  SearchAddress = 'SearchAddress',
  Alert = 'Alert',
  EventDetail = 'EventDetail',
  EventComment = 'EventComment',
  EventSelect = 'EventSelect',
  EventApply = 'EventApply',
  UserTicket = 'UserTicket',
  UserQR = 'UserQR',
  HostConsole = 'HostConsole',
  HostQRScan = 'HostQRScan',
  HostLedger = 'HostLedger',
  HostLedgerDetail = 'HostLedgerDetail',
  StaffManagement = 'StaffManagement',
  UserProfileEdit = 'UserProfileEdit',
  UserInterest = 'UserInterest',
  UserComment = 'UserComment',
  UserPasswordReset = 'UserPasswordReset',
  Scrap = 'Scrap',
}

export const enum BottomTabMenu {
  Home = 'Home',
  EventMap = 'EventMap',
  UserEvent = 'UserEvent',
  User = 'User',
}

export const enum AuthorizeMenu {
  Login = 'Login',
  AgreeToTerm = 'AgreeToTerm',
  PhoneCertification = 'PhoneCertification',
  EmailPassword = 'EmailPassword',
  Nickname = 'Nickname',
  UserInfo = 'UserInfo',
  InterestField = 'InterestField',
  JoinComplete = 'JoinComplete',
  EmailPasswordFind = 'EmailPasswordFind',
}
