const enum SelectStatus {
  SET_APPLICATION_ABLE_OPTION = 'SET_APPLICATION_ABLE_OPTION',
  SET_PARTICIPANT_OPTION = 'SET_PARTICIPANT_OPTION',
  SET_PAY_OPTION = 'SET_PAY_OPTION',
  RESET_SELECT = 'RESET_SELECT',
}

export default SelectStatus;
