const MENT_AUTHORIZE = Object.freeze({
  ERROR: {
    SERVER_ERROR: '서버에 오류가 발생했습니다.',
  },
  LOGIN: {
    LOGIN: '로그인',
    JOIN_THE_MEMBERSHIP: '회원가입',
    EMPTY_BAR: '   |   ',
    FIND_ID_PASSWORD: '아이디/비밀번호 찾기',
    INPUT_EMAIL: '이메일을',
    INPUT_PASSWORD: '비밀번호를',
    REQUEST_INPUT: '입력해주세요.',
    LOADING: '로그인 중입니다.',
    OR: '또는',
  },
  MAIN: {
    NEXT: '다음',
    EMAIL: '이메일',
    ID: '아이디',
    PASSWORD: '비밀번호',
  },
  FIND: {
    BACK_TO_LOGIN: '로그인 화면으로',
    RESET_PASSWORD: '비밀번호를 재설정해주세요.',
    NEW_PASSWORD: '새 비밀번호',
    INPUT_PASSWORD: '비밀번호를 입력해주세요',
    NEW_PASSWORD_CHECK: '새 비밀번호 확인',
    INPUT_PASSWORD_CHECK: '비밀번호 확인을 입력해주세요',
    SUCCESS_RESET_PASSWORD: '비밀번호 변경이 완료되었습니다.',
    LOGIN_INTRODUCTORY_COMMENT: '다시 로그인을 해주세요.',
    FIND_ID_RESULT: '아이디 찾기 결과입니다!',
    CANNOT_FIND_ID: '해당 핸드폰으로 등록된 아이디가 존재하지 않습니다!',
    NOT_MATCHED_USER_INFO:
      '회원정보가 일치하지 않습니다. 이메일과 핸드폰 번호를 확인해주세요.',
    FIND_ID: '아이디 찾기',
    FIND_PASSWORD: '비밀번호 찾기',
  },
  PHONE_CERTIFICATION: {
    TITLE: ['휴대폰 인증을 해주세요.'],
    PHONE_NUMBER: '휴대폰 번호',
    RESEND: '재발송',
    GET_CERTIFIED: '인증받기',
    CERTIFICATION_NUMBER: '인증번호',
    REMAINING_TIME: '남은 시간',
    SEND_CERTIFICATION_NUMBER_MESSAGE: '인증번호를 발송하였습니다.',
    DUPLICATED_USER_INFO: '이미 회원정보가 있는 핸드폰 번호입니다.',
  },
  INTEREST_FIELD: {
    UP_TO_THREE_CAN_BE_SELECTED: '최대 3가지 선택 가능',
    TITLE: ['관심 분야를 설정해주세요.'],
  },
  JOIN_COMPLETE: {
    TITLE: (nickname: string) => [`'${nickname}'님`, '회원가입을 축하합니다!'],
    MY_FIELD_TITLE: '나의 관심사는',
    START: '시작하기',
  },
  NICKNAME: {
    DUPLICATED_NICKNAME: '중복된 닉네임입니다. 다시 설정해주세요.',
    TITLE: ['오픈오프에서 사용할', '닉네임을 입력해주세요.'],
    CONFIRM: '확인',
    NICKNAME: '닉네임',
  },
  AGREE_TO_TERM: {
    CONFIRM: '확인',
    TITLE: ['서비스 이용 약관에', '동의해 주세요.'],
    ALL_AGREE: '네, 모두 동의합니다.',
    TERM_TO_TEENAGER: '(필수) 만 14세 이상입니다.',
    TERM_TO_USE: '(필수) 서비스 이용약관',
    TERM_TO_PRIVACY: '(필수) 개인정보 수집 이용',
    TERM_TO_MARKETING: '(선택) 마케팅 정보 수신동의',
  },
  USER_INFO: {
    TITLE: ['오픈오프 이용을 위해', '정보를 입력해주세요.'],
    NAME: '이름',
    BIRTH: '생일',
    SELECT_DATE: '날짜를 선택해주세요.',
    CONFIRM: '확인',
    APPLY: '적용',
    CANCEL: '닫기',
    GENDER: '성별',
    MAN: '남성',
    WOMAN: '여성',
  },
});

export default MENT_AUTHORIZE;
