const enum UserInfoStatus {
  SET_NAME = 'SET_NAME',
  SET_BIRTH = 'SET_BIRTH',
  SET_AGREE_TO_TERM = 'SET_AGREE_TO_TERM',
  SET_PHONE_NUMBER = 'SET_PHONE_NUMBER',
  SET_GENDER = 'SET_GENDER',
  SET_NICK_NAME = 'SET_NICK_NAME',
  SET_EMAIL_ADDRESS_PASSWORD = 'SET_EMAIL_ADDRESS_PASSWORD',
  SET_PASSWORD = 'SET_PASSWORD',
  SET_INTEREST_FIELD = 'SET_INTEREST_FIELD',
}

const enum GenderType {
  MAN = 'MAN',
  WOMAN = 'WOMAN',
}

export { GenderType, UserInfoStatus };
