const MENT_EVENT_MAP = Object.freeze({
  DATE_PICKER: {
    MONTH_NAMES: [
      '1월',
      '2월',
      '3월',
      '4월',
      '5월',
      '6월',
      '7월',
      '8월',
      '9월',
      '10월',
      '11월',
      '12월',
    ],
    MONTH_NAMES_EN: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ],
    DAY_NAMES: [
      '일요일',
      '월요일',
      '화요일',
      '수요일',
      '목요일',
      '금요일',
      '토요일',
    ],
    DAY_NAMES_EN: [
      'SUNDAY',
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
    ],
    DAY_NAMES_SHORT: ['일', '월', '화', '수', '목', '금', '토'],
    DAY_NAMES_SHORT_EN: ['Su', 'Mo', 'Tue', 'We', 'Th', 'Fr', 'Sa'],
  },
});

export default MENT_EVENT_MAP;
