const MENT_EVENT_MAP = Object.freeze({
  PERMISSION: {
    LOCATION: '오픈오프에 위치정보를 허용해주세요!',
  },
  MAIN: {
    CURRENT_FIELD_FIND: '현 지도에서 검색',
    DAY_FORMAT: 'MM월 YY일',
    SORT: {
      DATE: '날짜순',
      DISTANCE: '거리순',
    },
    SELECT_BOX: {
      FILTER: '필터',
      ALL: '전체',
      PAY: {
        LABEL: '비용',
        PAY: '유료',
        FREE: '무료',
      },
      PARTICIPANT: {
        LABEL: '참여 인원',
        SMALL: '20인 미만',
        MEDIUM: '20인 ~ 50인',
        LARGE: '50인 ~ 100인',
        HUGE: '100인 이상',
      },
      APPLICATION_ABLE: {
        LABEL: '신청 현황',
        APPLYING: '신청중',
        DEADLINE: '신청마감',
      },
      RESET: '초기화',
      APPLY: '적용',
    },
    SEARCH: {
      PLACEHOLDER: '지역, 이벤트 이름, 주최자 검색',
      DATE_FORMAT: (month: number, day: number) => `${month}월 ${day}일`,
    },
    EMPTY_EVENT: '이벤트 검색결과가 없습니다!',
  },
  DATE_PICKER: {
    TITLE: '기간',
    THIS_WEEK: '이번 주',
    NEXT_WEEK: '다음 주',
    DIRECT: '직접 입력',
    RESET: '초기화',
    APPLY: '적용',
    MONTH_NAMES: [
      '1월',
      '2월',
      '3월',
      '4월',
      '5월',
      '6월',
      '7월',
      '8월',
      '9월',
      '10월',
      '11월',
      '12월',
    ],
    MONTH_NAMES_SHORT: [
      '1월',
      '2월',
      '3월',
      '4월',
      '5월',
      '6월',
      '7월',
      '8월',
      '9월',
      '10월',
      '11월',
      '12월',
    ],
    DAY_NAMES: [
      '일요일',
      '월요일',
      '화요일',
      '수요일',
      '목요일',
      '금요일',
      '토요일',
    ],
    DAY_NAMES_SHORT: ['일', '월', '화', '수', '목', '금', '토'],
  },
});

export default MENT_EVENT_MAP;
